### PR TITLE
Refactor source into cmd pattern.

### PR DESCRIPTION
**Pull request by tanema**
Generally when writing a command line tool you shouldn't have any source in the main package. This is generally done when you are writing a library. The only thing that should remain in the main package are config, docs and makefile.

I also moved bucket into the main kit package since it was only ever used with leakybucket and that was only ever used by the themekit code.

I would like to refactor more but I didn't want the PR to get too big.

@chrisbutcher @ilikeorangutans

### CODE REVIEW

**Comment by tanema** [comment]
Also after this is done, I will get circle setup so we can run the tests that we actually have.

**Comment by ilikeorangutans** [comment]
So you moved the bulk of the classes from main into the kit package? Did you change all the package prefixes manually or do you have a handy tool?

**Comment by tanema** [comment]
Manually unfortunately. I don't know any tools that will rename things for you. That would be nice.

**Comment by tanema** [comment]
Okay so I rebased so the tests work so you can see the tests are passing. I also had to change the circle build so it would work without go get so it will be testing like we run tests (with vendor) Tests all pass and the command is still entirely functional.

**Comment by chrisbutcher** [comment]
LGTM

**Pull request merged**
