### PR TITLE
Feature automatic updater

### PR DESCRIPTION
**Pull request by csaunders**
This integrates `go-update` into the project so we can make it easier for users to upgrade from one version to the next.

Previously it required that when a new update came out the developer had to download a zip and overwrite their previous copy with a new one. This was error prone and made it hard to ensure users were always on the latest version.

With the `release` script in master, as a part of the release process we can upload the binaries to S3. With that functionality there we can now leverage that for future releases.

This also includes a version bump to `0.3.0` because of the newly added feature.

Fixes https://github.com/Shopify/themekit/issues/65
Fixes https://github.com/Shopify/themekit/issues/15

Please review @chrisbutcher

### CODE REVIEW

**Comment by csaunders** [comment]
Here is what the update required banner looks like:

screenshot 2015-09-18 09 44 21

**Comment by chrisbutcher** [comment]
One question at the outset: Do we need a test for update.go?

**Comment by csaunders** [comment]
I haven't done any testing for the `themekit/commands` package yet.

I know I should, but it's all CLI stuff.

I know... it's no excuse :(

**Comment by chrisbutcher** [comment]
No worries! Just making sure it's not an unintentional oversight! :smile:

**Comment by chrisbutcher** [comment]
LGTM!

**Pull request merged**
