### PR TITLE
expanded list of supported folders to include sections and blocks

### PR DESCRIPTION
**Pull request by stevebosworth**
@csaunders @ilikeorangutans 

Quick fix to support some new folders we need for themes going forward.  Let me know if there's any updates needed for tests and the like.

### CODE REVIEW

**Comment by ilikeorangutans** [comment]
Looks good to me and tests are passing for me.

**Comment by cshold** [comment]
:+1:

**Comment by rickydazla** [comment]
What are `sections` and `blocks`?

**Comment by cshold** [comment]
Some experimental folders we're working with internally right now. We added them here so we didn't have to create a private fork of the repo.

**Pull request merged**
